before_install:   - pip install --user cpp-coveralls

language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

after_success: - coveralls --exclude lib --exclude tests --gcov-options '\-lp'