language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

script: "sbt clean coverage test"

after_success: "sbt coveralls"